### ISSUE TITLE
Error in xy.coords(x, y, setLab = FALSE) : 'x' and 'y' lengths differ

### ISSUE THREAD

**Issue by Ma-Bar** [mjin1812/SMART#7]
Hi,
after playing the choice game `setup <- choice(setup, filetype = "tif")` I tried to run the midpoint check.
Unfortunately, after there was an ERROR `Error in xy.coords(x, y, setLab = FALSE) : 'x' and 'y' lengths differ`. I checked the internal AP coordinates and z numbers, and they are different indeed... not sure what caused the problem. Is there any solution to this problem?
![SMART_Error](https://user-images.githubusercontent.com/74044839/222434719-54483a34-2f29-4167-afa8-183e2ec08eaf.png)

**Comment by mjin1812** [comment]
Sorry about the late reply on this! Hmm it's hard to know what the issue is without seeing what your original setup list was like. But the error is caused by the mismatching lengths between your  vector of AP coordinates and the vector of matching z planes. 

Do you mind copy and pasting your original setup list? Did you successfully running the choice function and save the output to `setup` before trying `midpoint=TRUE`. It's possible the output didn't actually save.

Alternatively, you can try deleting the single AP coordinate that isn't matched correctly to the 6 z planes you have and continue running the rest of the pipeline with out that internal reference coordinate.

**Comment by Ma-Bar** [comment]
Thank you for your reply. This is my original setup:
![smart_issue_setup](https://user-images.githubusercontent.com/74044839/231447913-ff268731-9c7b-464c-bd1f-38458d0b4ae5.PNG)

I checked that there was the last z number missing. I manually added the correct missing number and continued the pipeline until the second issue, after running the autoloop command: `regi_loop(setup, autoloop = TRUE, filter = filter)`. The program stopped loading on plate 39 out of 132 and displayed: 
```
Error in transformationgrid$mx[index] : subscript out of bounds
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```
This problem I cannot walk around like previous one.

**Comment by mjin1812** [comment]
Okay, it may be helpful at this point to look at the raw data. Plate 39 matches AP coordinate + 1.50. Can you find the raw image used for registration based on the z coordinate that was matched to this plate? You can email me this image at mj2947@cumc.columbia.edu.

I typically see this issue in two cases: 1) Whenever there may be pieces of the tissue that intersects the boundaries of the image and 2) when the brain.threshold parameter in the filter used for your images is not optimized. One image where the boundaries of the tissue are not properly segmented from the background can throw the pipeline off. 

For the first case, you may need to pad your image with some black pixels. For the second case, I would look at how the autoregistration looks for all the previous slices. If the first pass registration looks off, you may need to change your brain.threshold to avoid this error. This error is occuring at the level of the base wholebrain registration function, so it is not happening because of the autolooping.

**Comment by mjin1812** [comment]
Copied email response below for reference for other users:

Thank you for your response and I hope this tool proves useful. I should have emphasized this in the tutorial, but finding the right filter parameters that work generally work to detect the boundaries of your tissue (outline in blue line) for all your images is imperative before being able to run the rest of the registration looping. This can be somewhat tested using the wholebrain segment() function. However, the GUI used to adjust the filter parameters is not great, and it's better to manually adjust the parameters by assignment. With some trial and error, I found what I think are pretty good parameters to use for your filter.

The two most import are the filter$resize​ parameter. I needed to set it higher to 0.4 to get the atlas within the bounds of the rendered graphic. This is because the resolution of your image is so high. I think this is the inverse of a constant needed to change the scale of the atlas (higher value = smaller atlas rendering). I would confer with the wholebrain documentation on this.

I also set the filter$brain.threshold​ to 600 to best separate the background from the foreground. I attached the filter as an RDATA object for you to load into your environment.

I've attached screenshots of how these parameters work for your image on my computer. Give it a try!

![image](https://user-images.githubusercontent.com/42684103/232798726-afc9d79d-eb0a-4ed5-a652-2bd2d004b100.png)
